version: "3.8"

services:
  app:
    image: node:12-alpine
    command: sh -c "yarn install && yarn run dev"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - 8080:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
    networks:
    - nw

  mysql:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    networks:
    - nw

volumes:
  db:

networks:
  nw: